### ISSUE TITLE
SwiftSyft Connection Clients Roadmap

### ISSUE THREAD

**Issue by mjjimenez** [OpenMined/SwiftSyft#3]
SwiftSyft establishes connection to a grid server (grid.js or pygrid) via a signalling server (websocket) and receives instructions (plans, protocols or tensor operations) sent by PySyft. The operations can be shared to other workers (mobile or web) via a WebRTC peer-to-peer connection.

In order to facilitate these functionality we're going to need three main components

**Components**
- [x] iOS 12 Socket connection
- [x] iOS 13 Socket connection
- [x] Signalling client
- [x] WebRTC client
- [ ] Syft client

**Components Description**

1. **iOS 12 and 13 Socket Connection implementation**
- Should conform to https://github.com/OpenMined/SwiftSyft/blob/master/SwiftSyft/Protocols/SocketClientProtocol.swift
- Socket client connection should have a periodic keep alive/ping : Reference: https://github.com/OpenMined/grid.js/blob/master/SOCKETS.md
- Assert that socket protocol should use `wss://`
- iOS 13 implementation should use 
- Should only be concerned with sending and receiving `Data` objects via `wss` connection. 

2. **Signalling client**:
- Should connect via `wss://` to a grid server (grid.js for now). Asser that the URL is `ws:/`
- Is initialized with a socket client implementation
- Serializes/Deserializes messages received or to be sent to/from the socket client.
- Be able to send and receive messages (Socket messages documentation can be found here: https://github.com/OpenMined/grid.js/blob/master/SOCKETS.md)
- Reference in syft.js workere is here (https://github.com/OpenMined/syft.js/blob/master/src/sockets.js)

3. **WebRTC client**
- Should establish and keep multi-peer connection and data channel from the connections it receives from the signalling client.
- Handles storing connections, data channels and ice candidates for each peer connection.
- Sends SDP offers/answers using signalling client.
- Should use `GoogleWebRTC` iOS library.
- Reference: https://github.com/OpenMined/syft.js/blob/master/src/webrtc.js

4. **Syft client**
- Handles coordination between signalling client and webrtc client.
- Stores business logic states (workerId and scopeId)
- Stores plans/protocols received from PySyft
- Reference: https://github.com/OpenMined/syft.js/blob/master/src/syft.js

5. **Messages**
- These are the messages sent among the grid server and mobile/web workers.
- For now, only socket messages (between workers and grid server) are defined
- Socket messages are serialized as JSON for now. PySyft protocols, on the other hand, are serialized in serde (custom serialization by Pysyft) by grid.js. We're not going to implement serde deserialization since eventually all the messages will be serialized in Protobuf. 
- Reference: https://github.com/OpenMined/grid.js/blob/master/SOCKETS.md

**Supporting features**

- [ ] Data channel chunking
- [ ] UI to specify server and peer connection

1. **Data Channel Chunking**
- Messages greater than 16 KB sent via WebRTC will have to be sent in 16 KB chunks.
- Reference is here: 
https://webrtc.github.io/samples/src/content/datachannel/datatransfer/

2. **UI**
- Specifies socket server to connect to
- Initiates connection to grid server via button tap

Edit:
* Added requirement to enforce `ws://` connection in signalling client.
