### ISSUE TITLE
Execute plans in iOS

### ISSUE THREAD

**Issue by cereallarceny** [OpenMined/SwiftSyft#33]
This epic issue is somewhat self-explanatory, but in theory, we need to be able to execute a PySyft plan. This should ideally only be done after the API has been finalized in the iOS worker (https://github.com/OpenMined/SwiftSyft/issues/28).

**Comment by mjjimenez** [comment]
Remaining tasks:
API:
- [ ] Model Download
- [ ] Model Report

Training
- [ ] Integrate Swift Syft-Proto stubs that were published in cocoapods
- [ ] Trigger error blocks
- [ ] Generate diffs
- [ ] Serialize `State` diff protobuff to send to PyGrid.
